# Generated by Django 2.2.4 on 2021-03-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_auto_20210322_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
    ]
