# Generated by Django 2.2.4 on 2021-03-30 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0003_remove_user_birth_date'),
        ('wallApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_for', to='loginApp.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='loginApp.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_from', to='loginApp.User'),
        ),
    ]
